---
- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: Add repository for nginx
  apt_repository:
    repo: deb http://nginx.org/packages/ubuntu/ focal nginx
    state: present
    filename: nginx

- name: update repositories cache && install nginx 
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Enable nginx
  systemd:
    name: nginx
    state: started
    enabled: yes

- name:  allow port 22
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: deny everything and enable UFW
  ufw:
    state: enabled
    policy: deny

- name: Allow 80,443 for nginx
  community.general.ufw:
    rule: allow
    port: '{{ item }}'
  loop:
    - 80
    - 443
    
- name: show version nginx
  shell: 
   cmd: nginx -v
  register: nginx

- name: debug nginx
  debug:
   msg: "{{ nginx.stdout }}"

- name: add vrrp protocol 
  ufw:
    rule: allow
    port: vrrp
    proto: tcp

- name: install keepalived
  apt:
    name: keepalived
    state: present

