---
- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: Add repository for nginx
  apt_repository:
    repo: deb http://nginx.org/packages/ubuntu/ focal nginx
    state: present
    filename: nginx

- name: update repositories cache && install nginx 
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: copy config file nginx
  copy:
    src: nginx.conf
    dest: /etc/nginx/conf.d/
    mode: '0644'
  notify: Restart nginx

- name: Enable nginx
  systemd:
    name: nginx
    state: started
    enabled: yes

- name:  allow port 22
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: deny everything and enable UFW
  ufw:
    state: enabled
    policy: deny

- name: Allow 80,443 for nginx
  community.general.ufw:
    rule: allow
    port: '{{ item }}'
  loop:
    - 80
    - 443
    
- name: show version nginx
  shell: 
   cmd: nginx -v
  register: nginx

- name: debug nginx
  debug:
   msg: "{{ nginx }}"

- name: Allow VRRP multicast address
  ufw:
    rule: allow
    src: 172.16.40.0/24
    dest: 224.0.0.18

- name: install keepalived
  apt:
    name: keepalived
    state: present

- name: copy keepalived config
  template:
    src: config.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0644'
  notify: Restart keepalived

- name: enable keepalived 
  systemd:
    name: keepalived
    state: started
    enabled: yes